AWSTemplateFormatVersion: 2010-09-09
Description: >-
  userdata-api

Transform:
- AWS::Serverless-2016-10-31

Resources:
  HelloRustFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloRust
      Handler: bootstrap.is.real.handler
      Runtime: provided
      MemorySize: 512
      CodeUri: .
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
    Metadata:
      BuildMethod: makefile
